name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  url_launcher: ^6.1.14
  json_annotation: ^4.8.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  http: any
  social_media_buttons:
    git:
      url: https://github.com/nrubin29/social_media_buttons
      ref: null-safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
